# version: '3.5'

# services:
#   db: 
#     container_name: db
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_PASSWORD=root
#       - POSTGRES_USER=postgres
#     image: postgres:13.11-bullseye
      
  
version: '3.8'

networks:
  default:

services:

  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    image: postgres:13.11-bullseye   

  nestjs-app:
    container_name: nestjs-app
    # depends_on:
    #   - mysql-db
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    environment:
      - DB_HOST=$POSTGRESQLDB_HOST
      - DB_USER=$POSTGRESQLDB_USER
      - DB_PASSWORD=$POSTGRESQLDB_PASSWORD
      - DB_DATABASE=$POSTGRESQLDB_DATABASE
      - DB_PORT=$POSTGRESQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - default
    
  nextjs-app:
    container_name: nextjs-app
    # depends_on: 
      # - nestjs-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default
